### ISSUE TITLE
Run description in README

### ISSUE THREAD

**Issue by jorgemorando** [Smedzlatko/spring-boot2-oauth2#1]
Hi @Smedzlatko!, i stumbled upon this repo from a spring security migration issue you opened about security adapter order configuration, im having the same problem and wanted to know if you could just provide a short README about how to run this example and some observations you might consider to be important please. 
Thanks in advance!!

**Comment by Smedzlatko** [comment]
Hi, could you, please, remind me of the issue? You did not provide a link and I don't remember what was the problem exactly.

**Comment by angelasrc** [comment]
Is this project running and working fine? Could you provide a short readme on how to run the example?

**Comment by Smedzlatko** [comment]
Hi, I added short README and Maven wrapper so you can now run the application without having to install Maven locally.

This repository was initially meant to provide a minimal example for demonstrating a certain bug I encountered. If you are looking for a more complex example (OAuth2 + Flyway), I suggest another project I created for this purpose: https://github.com/gigsterous/auth-server
